name: Build Docs

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python - --version 1.3.2
          poetry install --with docs --all-extras
          echo "PYTHONPATH=`pwd`" >> $GITHUB_ENV
      - name: Build Docs
        run: |
          sudo apt-get update -y && sudo apt-get install -y pandoc python3-pkg-resources python3-setuptools
          poetry run sphinx-build -b html -a docs docs/site
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site
